##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---deployment:
tasks:
- export DEPLOYPATH=/home/adleqkxi/sandbox.adlee.io/
- /bin/cp -R .vscode $DEPLOYPATH- /bin/cp -R assets $DEPLOYPATH
- /bin/cp index.html $DEPLOYPATH
